%'S-malyl N-Acetyl-alpha-D-glucosaminide'
newModel = addMetabolite(Model, 'glcnacmal[c]', ...
                         'metName', 'S-malyl N-acetyl-alpha-D-glucosaminide', ...
                         'metFormula', 'C12H17NO10', ...
                         'Charge', -2);
met_pos = strcmp(newModel.mets, 'glcnacmal[c]');
newModel.metChEBIID{met_pos} = 'CHEBI:64870';
newModel.metPubChemID{met_pos} = '57339291';
%'S-malyl alpha-D-glucosaminide'
newModel2 = addMetabolite(newModel, 'glcmal[c]', ...
                         'metName', 'S-malyl alpha-D-glucosaminide', ...
                         'metFormula', 'C10H16NO9', ...
                         'Charge', -1);
met_pos = strcmp(newModel2.mets, 'glcmal[c]');
newModel2.metChEBIID{met_pos} = 'CHEBI:64871';
newModel2.metPubChemID{met_pos} = '573392741';
%Bacillithiol
newModel3 = addMetabolite(newModel2, 'bacthiolbsh[c]', ...
                         'metName','Bacillithiol', ...
                         'metFormula', 'C13H22N2O10S', ...
                         'Charge', -1);
met_pos = strcmp(newModel3.mets, 'bacthiolbsh[c]');
newModel3.metChEBIID{met_pos} = 'CHEBI:64876';
newModel3.metPubChemID{met_pos} = '42614123';
%Oxidixed Bacillithiol
newModel4 = addMetabolite(newModel3, 'bacthiolbssb[c]', ...
                         'metName','Bacillithiol Disulfide', ...
                         'metFormula','C26H42N4O20S2', ...
                         'Charge', -2);
met_pos = strcmp(newModel4.mets, 'bacthiolbssb[c]');
newModel4.metChEBIID{met_pos} = 'CHEBI:12345';
newModel4.metPubChemID{met_pos} = '139583567';
%beta-1-3-galactobiose
newModel5 = addMetabolite(newModel4, 'b13galacbio[c]', ...
                         'metName', 'beta-1-3-galactobiocysteine', ...
                         'metFormula', 'C16H26N2O12S1', ...
                         'Charge', 0);